config/routes.rb
Rails.application.routes.draw do

  post 'entry_event/', to: 'entry_event#create'

  resources :attendances
  resources :events
  devise_for :users

  get 'home/index'
  root to: 'home#index'
  

end

app/models/admin.rb
class Admin < ActiveRecord::Base
	belongs_to :user
	belongs_to :event
end

app/models/attendance.rb
class Attendance < ActiveRecord::Base
	belongs_to :sub_event
	belongs_to :user
end

app/models/client.rb
class Client < ActiveRecord::Base
	belongs_to :user
	belongs_to :event
end

app/models/event.rb
class Event < ActiveRecord::Base
	has_many :sub_events

	has_many :admins
	has_many :admin_users, :through => :admins, :source => :user

	has_many :clients
	has_many :client_users, :through => :clients, :source => :user
end

app/models/sub_event.rb
class SubEvent < ActiveRecord::Base
	has_many :attendances
	belongs_to :event
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :attendances

	has_many :admins
	has_many :admin_events, :through => :admins, :source => :event
	has_many :clients
	has_many :client_events, :through => :clients, :source => :event

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_attendance, only: [:show, :edit, :update, :destroy]

  # GET /attendances
  # GET /attendances.json
  def index
    @attendances = Attendance.all
  end

  # GET /attendances/1
  # GET /attendances/1.json
  def show
  end

  # GET /attendances/new
  def new
    @attendance = Attendance.new
  end

  # GET /attendances/1/edit
  def edit
  end

  # POST /attendances
  # POST /attendances.json
  def create
    @attendance = Attendance.new(attendance_params)

    respond_to do |format|
      if @attendance.save
        format.html { redirect_to @attendance, notice: 'Attendance was successfully created.' }
        format.json { render :show, status: :created, location: @attendance }
      else
        format.html { render :new }
        format.json { render json: @attendance.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /attendances/1
  # PATCH/PUT /attendances/1.json
  def update
    respond_to do |format|
      if @attendance.update(attendance_params)
        format.html { redirect_to @attendance, notice: 'Attendance was successfully updated.' }
        format.json { render :show, status: :ok, location: @attendance }
      else
        format.html { render :edit }
        format.json { render json: @attendance.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /attendances/1
  # DELETE /attendances/1.json
  def destroy
    @attendance.destroy
    respond_to do |format|
      format.html { redirect_to attendances_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_attendance
      @attendance = Attendance.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def attendance_params
      params.require(:attendance).permit(:in, :out)
    end
end

app/controllers/entry_event_controller.rb
class EntryEventController < ApplicationController

	# PARAMS : user_id , beacon_id, time_in OR time_out, attendance_id

  def create

  	if has_attendance_id?
  		@attendance = Attendance.find_by_id(params[:attendance_id])	
  	else
  		@attendance = Attendance.new
  	end

  	if entry_action?
  		@attendance.in = params[:time_in]
  	else
  		@attendance.out = params[:time_out] # Time out must always come with attendance_id, otherwise will cause an error later on.
  	end

  	@event = Event.find_by beacon: params[:beacon_id] # If beacon is not linked to any event, next line will cause an error.
    @sub_event = SubEvent.where(:date => Date.today, :event_id => @event.id).first_or_create
  	
  	@attendance.user_id = params[:user_id]
  	@attendance.sub_event = @sub_event
  	@attendance.save

    respond_to do |format|
      if @attendance.save
        format.json { render :show, status: :created, location: @attendance }
      else
        format.json { render json: @attendance.errors, status: :unprocessable_entity }
      end
    end

  end

  private

  def entry_action?
  	params.has_key?(:time_in)
  end

  def has_attendance_id?
  	params.has_key?(:attendance_id)
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_timezone
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  def set_timezone
    Time.zone = 'Central Time (US & Canada)'
  end

  # GET /events
  # GET /events.json
  def index
    @events = current_user.admin_events
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    if !@event.admin_users.include? current_user
      @event.admin_users << current_user
    end

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:name, :start, :end, :beacon, admin_user_ids: [], client_user_ids: [])
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!

  def index
  	@admin_events = current_user.admin_events
  	@client_events = current_user.client_events
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/helpers/entry_event_helper.rb
module EntryEventHelper
end

app/helpers/events_helper.rb
module EventsHelper
	def time_status(event,attendance)
	    if attendance.in.between?(event.start, event.end)
	      return 'On Time'
	    else
	      return 'Late'
	    end
	end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/attendances/_form.html.erb
<%= form_for(@attendance) do |f| %>
  <% if @attendance.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@attendance.errors.count, "error") %> prohibited this attendance from being saved:</h2>

      <ul>
      <% @attendance.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :in %><br>
    <%= f.datetime_select :in %>
  </div>
  <div class="field">
    <%= f.label :out %><br>
    <%= f.datetime_select :out %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/attendances/edit.html.erb
<h1>Editing attendance</h1>

<%= render 'form' %>

<%= link_to 'Show', @attendance %> |
<%= link_to 'Back', attendances_path %>

app/views/attendances/index.html.erb
<h1>Listing attendances</h1>

<table>
  <thead>
    <tr>
      <th>In</th>
      <th>Out</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @attendances.each do |attendance| %>
      <tr>
        <td><%= attendance.in %></td>
        <td><%= attendance.out %></td>
        <td><%= link_to 'Show', attendance %></td>
        <td><%= link_to 'Edit', edit_attendance_path(attendance) %></td>
        <td><%= link_to 'Destroy', attendance, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Attendance', new_attendance_path %>

app/views/attendances/new.html.erb
<h1>New attendance</h1>

<%= render 'form' %>

<%= link_to 'Back', attendances_path %>

app/views/attendances/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>In:</strong>
  <%= @attendance.in %>
</p>

<p>
  <strong>Out:</strong>
  <%= @attendance.out %>
</p>

<%= link_to 'Edit', edit_attendance_path(@attendance) %> |
<%= link_to 'Back', attendances_path %>

app/views/entry_event/create.html.erb
<h1>EntryEvent#create</h1>
<p>Find me in app/views/entry_event/create.html.erb</p>

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>
      <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name, :class => "regLabel" %><br>
    <%= f.text_field :name, :class => "form-control" %>
  </div>
  <div class="field">
    <%= f.label :start, :class => "regLabel" %><br>
    <%= f.time_select :start, :class => "form-control", :ampm => 'true' %>
  </div>
  <div class="field">
    <%= f.label :end, :class => "regLabel" %><br>
    <%= f.time_select :end, :class => "form-control", :ampm => 'true' %>
  </div>
  <div class="field">
    <%= f.label :beacon, :class => "regLabel" %><br>
    <%= f.text_field :beacon, :class => "form-control" %>
  </div>
  <div class="field">
    <%= f.label :admins, :class => "regLabel" %><br>
    <%= collection_check_boxes(:event, :admin_user_ids, User.all, :id, :email) %>
  </div>
  <div class="field">
    <%= f.label :clients, :class => "regLabel" %><br>
    <%= collection_check_boxes(:event, :client_user_ids, User.all, :id, :email) %>
  </div>

  <div class="actions">
    <%= f.submit :class => "btn btn-blue signin-btn" %>
  </div>
<% end %>

app/views/events/edit.html.erb
<div id="wrapper">
  <nav class="navbar navbar-default navbar-fixed-top navbar-global" role="navigation">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#"><%= image_tag("logo-lg.png", :alt => "attendance tracker") %></a>
    </div>
    <div class="collapse navbar-collapse navbar-ex1-collapse">
      <ul class="nav navbar-nav side-nav">
        <% if false %>
        <li class="list-label">My Events:</li>
        <% @admin_events.each do |event| %>
        <li class="active"><%= link_to event.name, event %></li>
        <% end %>
        
        <li class="list-label-b">Event's I am Attending:</li>
        <% @client_events.each do |event| %>
        <li class="active"><%= link_to event.name, event %></li>
        <% end %>
        <% end %>
      </ul>
      <ul class="nav navbar-nav navbar-right navbar-user">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle user-dropdown" data-toggle="dropdown"><%= current_user.email %><b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><%= link_to 'Logout', destroy_user_session_path, :method => :delete %></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </nav>
      <div id="page-wrapper">
        <div class="row">
        <div class="col-sm-5 col-sm-offset-3 main">
        <div class="row cont-row-b">
          <h3 class="sub-header">Editing event</h3>
          <%= render 'form' %>
          <span class="event-links">
		  <%= link_to 'Show', @event %> |
          <%= link_to 'Back', events_path %>
      	  </span>
        </div>
      </div>
    </div><!-- /.row -->
  </div><!-- /#page-wrapper -->
</div><!-- /#wrapper -->

app/views/events/index.html.erb
<div id="wrapper">
  <nav class="navbar navbar-default navbar-fixed-top navbar-global" role="navigation">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#"><%= image_tag("logo-lg.png", :alt => "attendance tracker") %></a>
    </div>
    <div class="collapse navbar-collapse navbar-ex1-collapse">
      <ul class="nav navbar-nav side-nav">
        <% if false %>
        <li class="list-label">My Events:</li>
        <% @admin_events.each do |event| %>
        <li class="active"><%= link_to event.name, event %></li>
        <% end %>
        
        <li class="list-label-b">Event's I am Attending:</li>
        <% @client_events.each do |event| %>
        <li class="active"><%= link_to event.name, event %></li>
        <% end %>
        <% end %>
      </ul>
      <ul class="nav navbar-nav navbar-right navbar-user">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle user-dropdown" data-toggle="dropdown"><%= current_user.email %><b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><%= link_to 'Logout', destroy_user_session_path, :method => :delete %></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </nav>
      <div id="page-wrapper">
        <div class="row">
        <div class="col-sm-12 main">
        <div class="row cont-row-b">
          <h3 class="sub-header">Listing Events</h3>
          <div class="table-responsive">
            <table class="table table-striped">
              <thead>
                <tr>
                  <th>Name</th>
                  <th>Start</th>
                  <th>End</th>
                  <th>Beacon</th>
                </tr>
              </thead>
              <tbody>
                <% @events.each do |event| %>
                  <tr>
                    <td><%= event.name %></td>
                    <td><%= event.start.strftime("%I:%M %p") %></td>
                    <td><%= event.end.strftime("%I:%M %p") %></td>
                    <td><%= event.beacon %></td>
                    <td><span class="pull-right"><%= link_to 'Show', event, :class => 'btn btn-primary' %>
                    <%= link_to 'Edit', edit_event_path(event), :class => 'btn btn-info' %>
                    <%= link_to 'Delete', event, :class => 'btn btn-danger', method: :delete, data: { confirm: 'Are you sure?' } %></span></td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
          <%= link_to 'New Event', new_event_path, :class => 'btn btn-blue signin-btn' %>
        </div>
      </div>
    </div><!-- /.row -->
  </div><!-- /#page-wrapper -->
</div><!-- /#wrapper -->

app/views/events/new.html.erb
<div id="wrapper">
  <nav class="navbar navbar-default navbar-fixed-top navbar-global" role="navigation">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#"><%= image_tag("logo-lg.png", :alt => "attendance tracker") %></a>
    </div>
    <div class="collapse navbar-collapse navbar-ex1-collapse">
      <ul class="nav navbar-nav side-nav">
        <% if false %>
        <li class="list-label">My Events:</li>
        <% @admin_events.each do |event| %>
        <li class="active"><%= link_to event.name, event %></li>
        <% end %>
        
        <li class="list-label-b">Event's I am Attending:</li>
        <% @client_events.each do |event| %>
        <li class="active"><%= link_to event.name, event %></li>
        <% end %>
        <% end %>
      </ul>
      <ul class="nav navbar-nav navbar-right navbar-user">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle user-dropdown" data-toggle="dropdown"><%= current_user.email %><b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><%= link_to 'Logout', destroy_user_session_path, :method => :delete %></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </nav>
      <div id="page-wrapper">
        <div class="row">
        <div class="col-sm-5 col-sm-offset-3 main">
        <div class="row cont-row-b">
          <h3 class="sub-header">New event</h3>
          <%= render 'form' %>
		  <%= link_to 'Back', events_path %>
        </div>
      </div>
    </div><!-- /.row -->
  </div><!-- /#page-wrapper -->
</div><!-- /#wrapper -->

app/views/events/show.html.erb
<div id="wrapper">
  <nav class="navbar navbar-default navbar-fixed-top navbar-global" role="navigation">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#"><%= image_tag("logo-lg.png", :alt => "attendance tracker") %></a>
    </div>
    <div class="collapse navbar-collapse navbar-ex1-collapse">
      <ul class="nav navbar-nav side-nav">
        <li class="list-label">My Events:</li>
        <% current_user.admin_events.each do |event| %>
        <li class="active"><%= link_to event.name, event %></li>
        <% end %>
      </ul>
      <ul class="nav navbar-nav navbar-right navbar-user">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle user-dropdown" data-toggle="dropdown">
            <%= current_user.email %><b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to 'Logout', destroy_user_session_path, :method => :delete %></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </nav>     
  <div id="page-wrapper">
    <div class="row">
    <div class="col-sm-12 main">
    <div class="row cont-row-b">
      <h3 class="sub-header"><%= @event.name %>
        <span class="event-links">
          <%= link_to 'Edit', edit_event_path(@event) %> | <%= link_to 'Back', events_path %>
        </span>
      </h3>
      <p>
        <strong>Start:</strong>
        <%= @event.start.strftime("%I:%M %p") %>
      </p>
      <p>
        <strong>End:</strong>
        <%= @event.end.strftime("%I:%M %p") %>
      </p>
      <p style="margin-bottom:40px;">
        <strong>Beacon:</strong>
        <%= @event.beacon %>
      </p>
      <div class="table-responsive">
        <table class="table table-striped">
          <thead>
            <tr>
              <th>Admins:</th>
            </tr>
          </thead>
          <tbody>
            <% @event.admin_users.each do |user| %>
              <tr>
                <td><%= user.email %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
      <div class="table-responsive">
        <table class="table table-striped">
          <thead>
            <tr>
              <th>Attendees:</th>
            </tr>
          </thead>
          <tbody>
              <% @event.client_users.each do |user| %>
                <tr>
                  <td><%= user.email %></td>
                </tr>
              <% end %>
          </tbody>
        </table>
      </div>
    </div>
    <div class="row cont-row-b2">
      <div class="table-responsive">
        <% @event.sub_events.each do |sub_event| %>
          <h4><%= sub_event.date %></h4>

          <table class="table table-striped">
          <thead>
            <tr>
              <th align="left">Email:</th>
              <th align="left">Time In:</th>
              <th align="left">Time Out:</th>
              <th align="left">Status:</th>
            </tr>
          </thead>
          <tbody>
          <% sub_event.attendances.each do |attendance| %>
            <% if @event.client_users.include? attendance.user %>
              <tr>
                <td><%= attendance.user.email %></td>
                <td>
                  <% if !attendance.in.nil? %> 
                    <%= attendance.in.strftime("%I:%M %p") %>
                  <% end %>
                </td>
                <td>
                <% if !attendance.out.nil? %> 
                  <%= attendance.out.strftime("%I:%M %p") %>
                <% end %>
                </td>
                <td>
                <% if !attendance.in.nil? %>
                  <%= time_status(@event,attendance) %>
                <% end %>
                </td>
              </tr>
            <% end %>
          <% end %>
          </tbody>
        </table>
        <% end %>
      </div>
    </div>
    </div>
  </div><!-- /.row -->
  </div><!-- /#page-wrapper -->
</div><!-- /#wrapper -->

app/views/home/index.html.erb
<div id="wrapper">
  <nav class="navbar navbar-default navbar-fixed-top navbar-global" role="navigation">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#"><%= image_tag("logo-lg.png", :alt => "attendance tracker") %></a>
    </div>
    <div class="collapse navbar-collapse navbar-ex1-collapse">
      <ul class="nav navbar-nav side-nav">
        <li class="list-label">My Events:</li>
        <% @admin_events.each do |event| %>
          <li class="active"><%= link_to event.name, event %></li>
        <% end %>
      </ul>
      <ul class="nav navbar-nav navbar-right navbar-user">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle user-dropdown" data-toggle="dropdown"><%= current_user.email %><b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><%= link_to 'Logout', destroy_user_session_path, :method => :delete %></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </nav>
  <div id="page-wrapper">
    <div class="row">
    <div class="col-sm-12 main">
    <div class="row cont-row-b">
      <h3 class="sub-header">Welcome!</h3>
      <div class="col-xs-12 home-h1">What would you like to do?</div>
      <div class="col-xs-12 new-btns">
        <div class="cont-row-c">
          <%= image_tag("list-icon.png", :alt => "list icon") %>
          <%= link_to 'New Event', new_event_path %>
        </div>
        <div class="cont-row-c">
          <%= image_tag("list-icon.png", :alt => "list icon") %>
          <%= link_to 'View All Events', events_path %>
        </div>
      </div>
    </div>
  </div>
  </div>
  </div><!-- /.row -->
</div><!-- /#page-wrapper -->
</div><!-- /#wrapper -->

app/views/layouts/_user_widget.html.erb
<% if user_signed_in? %>
  <!-- <p>Welcome <%= current_user.email %></p> -->
  <!-- <%= link_to 'Logged In [click to logout]', destroy_user_session_path, :method => :delete %> -->
<% else %>
  <!-- <p>You are not signed in.</p> -->
  <!-- <%= link_to 'Login', new_user_session_path %> -->
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>AttendanceTracker</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

<%= render 'layouts/user_widget' %>


	<div id="footer">
	  <div class="container">
	    <p class="text-muted">Senior Seminar 2014   |   St. Edward's Univeristy</p>
	  </div>
	</div>
</body>
</html>